---
- name: Clone eclipse.jdt.ls
  git:
    repo: https://github.com/eclipse/eclipse.jdt.ls
    dest: ~/dev/eclipse/eclipse.jdt.ls
- name: Build eclipse.jdt.ls
  command: ./mvnw clean install -DskipTests
  args:
    chdir: ~/dev/eclipse/eclipse.jdt.ls
- name: Create apps folder
  file:
    path: ~/apps/
    state: directory
    mode: 0700
- name: Create async-profiler folder
  file:
    path: ~/apps/async-profiler/
    state: directory
    mode: 0700
- name: Fetch sjk.jar
  get_url:
    url: https://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.gridkit.jvmtool&a=sjk&v=LATEST
    dest: ~/apps/sjk.jar
- name: Get and unpack async-profiler
  unarchive:
    src: https://github.com/jvm-profiling-tools/async-profiler/releases/download/v1.7/async-profiler-1.7-linux-x64.tar.gz
    dest: ~/apps/async-profiler/
    remote_src: true
    creates: ~/apps/async-profiler/profiler.sh
