---
- name: Install dev packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - base-devel
      - jq
      - ripgrep
      - fd
      - bash-language-server
      - lua-language-server
      - yaml-language-server
      - vscode-json-languageserver
      - vscode-html-languageserver
      - rust-analyzer
      - hub
      - luarocks
      - stylua
      - ninja
      - fzf
      - fzy
      - htop
      - delve
      - lldb
      - python-docutils  # rst2html is used by vale

- name: Install linters
  become: true
  ansible.builtin.package:
    state: present
    name:
      - codespell
      - shellcheck
