---
- name: Install dev packages
  become: true
  package:
    state: present
    name:
      - base-devel
      - jq
      - ripgrep
      - bash-language-server
      - lua-language-server
      - hub
      - luarocks
      - stylua
      - ninja
      - fzf
      - fzy
      - htop
      - delve
