---
- name: Clone tree-sitter repos
  git:
    repo: https://github.com/{{ item.repo }}
    dest: ~/dev/{{ item.repo }}
    version: '{{ item.version }}'
  loop:
    - { repo: 'tree-sitter/tree-sitter-java', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-python', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-html', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-json', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-haskell', version: 'master' }
    - { repo: 'nvim-treesitter/tree-sitter-lua', version: 'master' }
    - { repo: 'stsewd/tree-sitter-rst', version: 'master' }
    - { repo: 'ikatyang/tree-sitter-markdown', version: 'master' }
- name: Ensure nvim parser and query folders exists
  file:
    path: ~/.config/nvim/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - parser/
    - queries/
    - queries/java
    - queries/python
    - queries/lua
    - queries/rst
    - queries/html
    - queries/json
    - queries/haskell
    - queries/markdown

- name: Generate parsers
  command: cc -O2 -o ~/.config/nvim/parser/{{ item.ft }}.so -I./src {{ item.files }} -shared -Os -lstdc++ -fPIC
  args:
    chdir: ~/dev/{{ item.repo }}
  loop:
    - repo: 'tree-sitter/tree-sitter-java'
      ft: 'java'
      files: src/parser.c
    - repo: 'tree-sitter/tree-sitter-python'
      ft: 'python'
      files: src/parser.c src/scanner.cc
    - repo: 'tree-sitter/tree-sitter-haskell'
      ft: 'haskell'
      files: src/parser.c src/scanner.cc 
    - repo: 'tree-sitter/tree-sitter-html'
      ft: 'html'
      files: src/parser.c src/scanner.cc
    - repo: 'nvim-treesitter/tree-sitter-lua'
      ft: 'lua'
      files: src/parser.c src/scanner.cc
    - repo: 'stsewd/tree-sitter-rst'
      ft: 'rst'
      files: src/parser.c src/scanner.c
    - repo: 'tree-sitter/tree-sitter-json'
      ft: 'json'
      files: src/parser.c
    - repo: 'ikatyang/tree-sitter-markdown'
      ft: 'markdown'
      files: src/parser.c src/scanner.cc

- name: Copy queries
  copy:
    src: ~/dev/{{ item.src_dir }}/{{ item.file }}
    dest: ~/.config/nvim/queries/{{ item.ft }}/{{ item.file }}
  loop:
    - { ft: 'java', src_dir: 'tree-sitter/tree-sitter-java/queries', file: 'tags.scm' }
    - { ft: 'python', src_dir: 'tree-sitter/tree-sitter-python/queries', file: 'highlights.scm' }
    - { ft: 'python', src_dir: 'tree-sitter/tree-sitter-python/queries', file: 'tags.scm' }
    - { ft: 'html', src_dir: 'tree-sitter/tree-sitter-html/queries', file: 'highlights.scm' }
    - { ft: 'haskell', src_dir: 'tree-sitter/tree-sitter-haskell/queries', file: 'highlights.scm' }

- name: Fetch queries
  get_url:
    url: https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/{{ item.ft }}/{{ item.name }}.scm
    dest: ~/.config/nvim/queries/{{ item.ft }}/{{ item.name }}.scm
  loop:
    - { ft: 'lua', name: 'highlights' }
    - { ft: 'json', name: 'highlights' }
    - { ft: 'java', name: 'highlights' }
    - { ft: 'markdown', name: 'highlights' }
    - { ft: 'markdown', name: 'injections' }
