---
- name: Clone tree-sitter language repos
  git:
    repo: https://github.com/{{ item }}
    dest: ~/dev/{{ item }}
  loop:
    - tree-sitter/tree-sitter-java
    - tree-sitter/tree-sitter-python
    - Azganoth/tree-sitter-lua
- name: Ensure nvim parser folder exists
  file:
    path: ~/.config/nvim/parser/
    state: directory
    mode: '0755'
- name: Generate java parser
  command: cc -O2 -o ~/.config/nvim/parser/java.so -shared src/parser.c -I./src
  args:
    chdir: ~/dev/tree-sitter/tree-sitter-java

- name: Generate python parser
  command: cc -O2 -o ~/.config/nvim/parser/python.so -shared src/parser.c -I./src
  args:
    chdir: ~/dev/tree-sitter/tree-sitter-python

- name: Generate lua parser
  command: cc -O2 -o ~/.config/nvim/parser/lua.so -shared src/parser.c -I./src
  args:
    chdir: ~/dev/Azganoth/tree-sitter-lua/
