---
- name: Clone tree-sitter repos
  git:
    repo: https://github.com/{{ item.repo }}
    dest: ~/dev/{{ item.repo }}
    version: '{{ item.version }}'
  loop:
    -  { repo: 'tree-sitter/tree-sitter-java', version: 'f7b62ac33d63bea56ce202ace107aaa4285e50af' }
    -  { repo: 'tree-sitter/tree-sitter-python', version: 'd245768132eb6cb74d8a394ca4d29dc57169b096' }
    -  { repo: 'Azganoth/tree-sitter-lua', version: 'd835774e14fd7073567358cdb8900c6012ea5eef' }
- name: Ensure nvim parser and query folders exists
  file:
    path: ~/.config/nvim/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - parser/
    - queries/
    - queries/java
    - queries/python
    - queries/lua

- name: Generate java parser
  command: cc -O2 -o ~/.config/nvim/parser/java.so -shared src/parser.c -I./src
  args:
    chdir: ~/dev/tree-sitter/tree-sitter-java
- name: Generate python parser
  command: cc -O2 -o ~/.config/nvim/parser/python.so -I./src src/parser.c src/scanner.cc -shared -Os -lstdc++
  args:
    chdir: ~/dev/tree-sitter/tree-sitter-python
- name: Generate lua parser
  command: cc -O2 -o ~/.config/nvim/parser/lua.so -I./src src/parser.c src/scanner.cc -shared -Os -lstdc++
  args:
    chdir: ~/dev/Azganoth/tree-sitter-lua/

- name: Copy queries
  copy:
    src: ~/dev/{{ item.src_dir }}/{{ item.file }}
    dest: ~/.config/nvim/queries/{{ item.ft }}/{{ item.file }}
  loop:
    - { ft: 'java', src_dir: 'tree-sitter/tree-sitter-java/queries', file: 'highlights.scm' }
    - { ft: 'java', src_dir: 'tree-sitter/tree-sitter-java/queries', file: 'tags.scm' }
    - { ft: 'python', src_dir: 'tree-sitter/tree-sitter-python/queries', file: 'highlights.scm' }
    - { ft: 'python', src_dir: 'tree-sitter/tree-sitter-python/queries', file: 'tags.scm' }
- name: Fetch lua highlights
  get_url:
    url: https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/lua/highlights.scm
    dest: ~/.config/nvim/queries/lua/highlights.scm
