---
- name: Clone tree-sitter language repos
  git:
    repo: https://github.com/{{ item }}
    dest: ~/dev/{{ item }}
  loop:
    - tree-sitter/tree-sitter-java
    - tree-sitter/tree-sitter-python
    - Azganoth/tree-sitter-lua
- name: Generate parsers
  command: tree-sitter test
  args:
    chdir: ~/dev/{{ item }}
  loop:
    - tree-sitter/tree-sitter-java
    - tree-sitter/tree-sitter-python
    - Azganoth/tree-sitter-lua
- name: Create symlink for neovim to pick up tree-sitter parsers
  file:
    src: ~/.tree-sitter/bin
    dest: ~/.config/nvim/parser
    state: link
