---
- name: Clone tree-sitter repos
  git:
    repo: https://github.com/{{ item.repo }}
    dest: ~/dev/{{ item.repo }}
    version: '{{ item.version }}'
    force: true
  async: 30
  poll: 0
  register: git_clone
  loop:
    - { repo: 'tree-sitter/tree-sitter-java', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-python', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-html', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-json', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-haskell', version: 'master' }
    - { repo: 'tree-sitter/tree-sitter-c-sharp', version: 'master' }
    - { repo: 'MunifTanjim/tree-sitter-lua', version: 'main' }
    - { repo: 'stsewd/tree-sitter-rst', version: 'master' }
    - { repo: 'ikatyang/tree-sitter-markdown', version: 'master' }
    - { repo: 'vigoux/tree-sitter-viml', version: 'master' }
    - { repo: 'maxxnino/tree-sitter-zig', version: 'main' }
    - { repo: 'ikatyang/tree-sitter-yaml', version: 'master' }
- name: Ensure nvim parser and query folders exists
  file:
    path: ~/.config/nvim/{{ item }}
    state: directory
    mode: '0755'
  loop:
    - parser/
    - queries/
    - queries/java
    - queries/python
    - queries/lua
    - queries/rst
    - queries/html
    - queries/json
    - queries/haskell
    - queries/markdown
    - queries/vim
    - queries/c_sharp
    - queries/zig
    - queries/yaml

- name: Wait for git clone
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: git_clone_jobs
  until: git_clone_jobs.finished
  loop: "{{ git_clone.results }}"

- name: Generate parsers
  shell: tree-sitter generate --abi 14 && cc -O2 -o ~/.config/nvim/parser/{{ item.ft }}.so -I./src {{ item.files }} -shared -Os -lstdc++ -fPIC
  async: 120
  poll: 0
  register: compile_parsers
  args:
    chdir: ~/dev/{{ item.repo }}
  loop:
    - repo: 'tree-sitter/tree-sitter-java'
      ft: 'java'
      files: src/parser.c
    - repo: 'tree-sitter/tree-sitter-python'
      ft: 'python'
      files: src/parser.c src/scanner.cc
    - repo: 'tree-sitter/tree-sitter-haskell'
      ft: 'haskell'
      files: src/parser.c src/scanner.c
    - repo: 'tree-sitter/tree-sitter-html'
      ft: 'html'
      files: src/parser.c src/scanner.cc
    - repo: 'MunifTanjim/tree-sitter-lua'
      ft: 'lua'
      files: src/parser.c src/scanner.c
    - repo: 'stsewd/tree-sitter-rst'
      ft: 'rst'
      files: src/parser.c src/scanner.c
    - repo: 'tree-sitter/tree-sitter-json'
      ft: 'json'
      files: src/parser.c
    - repo: 'ikatyang/tree-sitter-markdown'
      ft: 'markdown'
      files: src/parser.c src/scanner.cc
    - repo: 'vigoux/tree-sitter-viml'
      ft: 'vim'
      files: src/parser.c src/scanner.c
    - repo: 'tree-sitter/tree-sitter-c-sharp'
      ft: 'c_sharp'
      files: src/parser.c src/scanner.c
    - repo: 'maxxnino/tree-sitter-zig'
      ft: 'zig'
      files: src/parser.c
    - repo: 'ikatyang/tree-sitter-yaml'
      ft: 'yaml'
      files: src/parser.c src/scanner.cc

- name: Wait for compile parsers
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: compile_jobs
  until: compile_jobs.finished
  loop: "{{ compile_parsers.results }}"

- name: Copy queries
  copy:
    src: ~/dev/{{ item.src_dir }}/{{ item.file }}
    dest: ~/.config/nvim/queries/{{ item.ft }}/{{ item.file }}
    mode: 0644
  loop:
    - { ft: 'java', src_dir: 'tree-sitter/tree-sitter-java/queries', file: 'tags.scm' }
    - { ft: 'html', src_dir: 'tree-sitter/tree-sitter-html/queries', file: 'highlights.scm' }
    - { ft: 'haskell', src_dir: 'tree-sitter/tree-sitter-haskell/queries', file: 'highlights.scm' }
    - { ft: 'zig', src_dir: 'maxxnino/tree-sitter-zig/queries', file: 'highlights.scm' }
    - { ft: 'zig', src_dir: 'maxxnino/tree-sitter-zig/queries', file: 'injections.scm' }

- name: Fetch queries
  get_url:
    url: https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/{{ item.ft }}/{{ item.name }}.scm
    dest: ~/.config/nvim/queries/{{ item.ft }}/{{ item.name }}.scm
  loop:
    - { ft: 'lua', name: 'highlights' }
    - { ft: 'lua', name: 'locals' }
    - { ft: 'lua', name: 'injections' }
    - { ft: 'json', name: 'highlights' }
    - { ft: 'java', name: 'highlights' }
    - { ft: 'java', name: 'locals' }
    - { ft: 'python', name: 'highlights' }
    - { ft: 'python', name: 'locals' }
    - { ft: 'markdown', name: 'highlights' }
    - { ft: 'markdown', name: 'injections' }
    - { ft: 'rst', name: 'highlights' }
    - { ft: 'rst', name: 'injections' }
    - { ft: 'vim', name: 'highlights' }
    - { ft: 'vim', name: 'injections' }
    - { ft: 'vim', name: 'locals' }
    - { ft: 'yaml', name: 'highlights' }
    - { ft: 'yaml', name: 'locals' }
    - { ft: 'yaml', name: 'injections' }

- name: Fetch csharp queries
  get_url:
    url: https://raw.githubusercontent.com/nvim-treesitter/nvim-treesitter/master/queries/c_sharp/{{ item }}.scm
    dest: ~/.config/nvim/queries/c_sharp/{{ item }}.scm
  loop:
    - highlights
    - injections
    - locals
