---
- name: Ensure jdks folder exists
  file:
    path: ~/.local/jdks/
    state: directory

- name: Install jdks
  ansible.builtin.unarchive:
    src: "https://github.com/adoptium/temurin{{ item.major }}-binaries/releases/download/jdk-{{ item.version }}/OpenJDK{{ item.major }}U-jdk_x64_linux_hotspot_{{ item.version|replace('+', '_') }}.tar.gz"
    dest: ~/.local/jdks/
    creates: ~/.local/jdks/jdk-{{ item }}
    remote_src: true
  loop:
    - { major: 17, version: "17.0.4+8" }
    - { major: 18, version: "18.0.2+9" }

- name: Install panama early access
  unarchive:
    src: https://download.java.net/java/early_access/panama/1/openjdk-19-panama+1-13_linux-x64_bin.tar.gz
    dest: ~/.local/jdks/
    remote_src: true
    extra_opts:
      - --transform
      - s/jdk-19/jdk-19ea-panama/

- name: Install GraalVM Java17
  unarchive:
    src: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java17-linux-amd64-22.1.0.tar.gz
    dest: ~/.local/jdks/
    creates: ~/.local/jdks/graalvm-ce-java17-22.1.0/
    remote_src: true
