---
- name: Ensure jdks folder exists
  file:
    path: ~/.local/jdks/
    state: directory

- name: Install jdks
  ansible.builtin.unarchive:
    src: "https://github.com/adoptium/temurin{{ item.major }}-binaries/releases/download/jdk-{{ item.version }}/OpenJDK{{ item.major }}U-jdk_x64_linux_hotspot_{{ item.version|replace('+', '_') }}.tar.gz"
    dest: ~/.local/jdks/
    creates: ~/.local/jdks/jdk-{{ item.version }}
    remote_src: true
  loop:
    - { major: 17, version: "17.0.6+10" }
    - { major: 19, version: "19.0.2+7" }

- name: Install GraalVM Java17
  unarchive:
    src: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java17-linux-amd64-22.3.0.tar.gz
    dest: ~/.local/jdks/
    creates: ~/.local/jdks/graalvm-ce-java17-22.3.0/
    remote_src: true
