---
- name: Ensure jdks folder exists
  file:
    path: ~/.local/jdks/
    state: directory

- name: Install openjdk 12
  unarchive:
    src: https://github.com/AdoptOpenJDK/openjdk12-binaries/releases/download/jdk-12.0.2%2B10/OpenJDK12U-jdk_x64_linux_hotspot_12.0.2_10.tar.gz
    dest: ~/.local/jdks/
    creates: ~/.local/jdks/jdk-12.0.2+10
    remote_src: true

- name: Install jdk 16
  unarchive:
    src: https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.1%2B9/OpenJDK16U-jdk_x64_linux_hotspot_16.0.1_9.tar.gz
    dest: ~/.local/jdks/jdk-16.0.1+9/
    remote_src: true
