---
- name: Ensure jdks folder exists
  ansible.builtin.file:
    path: ~/.m2/jdks/
    state: directory
    recurse: true

- name: Install jdks
  ansible.builtin.unarchive:
    src: "https://github.com/adoptium/temurin{{ item.major }}-binaries/releases/download/jdk-{{ item.version }}/OpenJDK{{ item.major }}U-jdk_x64_linux_hotspot_{{ item.version|replace('+', '_') }}.tar.gz"
    dest: ~/.m2/jdks/
    creates: ~/.m2/jdks/jdk-{{ item.version }}
    remote_src: true
  loop:
    - { major: 17, version: "{{ jdk17 }}" }
    - { major: 18, version: "{{ jdk18 }}" }
    - { major: 19, version: "{{ jdk19 }}" }
    - { major: 20, version: "{{ jdk20 }}" }

- name: Install GraalVM Java17
  ansible.builtin.unarchive:
    src: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java17-linux-amd64-22.3.0.tar.gz
    dest: ~/.m2/jdks/
    creates: ~/.m2/jdks/graalvm-ce-java17-22.3.0/
    remote_src: true
