---
- name: Ensure jdks folder exists
  file:
    path: ~/.local/jdks/
    state: directory

- name: Install jdk 15
  unarchive:
    src: https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.2%2B7/OpenJDK15U-jdk_x64_linux_hotspot_15.0.2_7.tar.gz
    dest: ~/.local/jdks/
    creates: ~/.local/jdks/jdk-15.0.2+7
    remote_src: true

- name: Install jdk 16
  unarchive:
    src: https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.1%2B9/OpenJDK16U-jdk_x64_linux_hotspot_16.0.1_9.tar.gz
    dest: ~/.local/jdks/
    creates: ~/.local/jdks/jdk-16.0.1+9
    remote_src: true

- name: Install panama early access
  unarchive:
    src: https://download.java.net/java/early_access/panama/3/openjdk-17-panama+3-167_linux-x64_bin.tar.gz
    dest: ~/.local/jdks/
    remote_src: true
    extra_opts:
      - --transform
      - s/jdk-17/jdk-17ea-panama/

- name: Install GraalVM Java16
  unarchive:
    src: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.1.0/graalvm-ce-java16-linux-amd64-21.1.0.tar.gz
    dest: ~/.local/jdks/
    creates: ~/.local/jdks/graalvm-ce-java16-21.1.0/
    remote_src: true
