---
- name: Setup neovim virtualenv
  pip:
    name:
      - pynvim
      - neovim-remote
    virtualenv: ~/.virtualenvs/nvim
    virtualenv_command: /usr/bin/python3 -m venv
- name: Symlink neovim remote
  file:
    src: ~/.virtualenvs/nvim/bin/nvr
    dest: ~/bin/nvr
    state: link
- name: Checkout vim plugins
  git:
    repo: https://github.com/{{ item }}
    dest: ~/.config/nvim/pack/plugins/start/{{ item | basename }}
  loop:
    - sainnhe/gruvbox-material
    - junegunn/gv.vim
    - junegunn/vim-easy-align
    - tpope/vim-fugitive
    - tpope/vim-rhubarb
    - gpanders/editorconfig.nvim
    - AndrewRadev/linediff.vim
    - hynek/vim-python-pep8-indent
    - jamessan/vim-gnupg
    - L3MON4D3/LuaSnip
    - liuchengxu/vista.vim
    - janko-m/vim-test
    - phaazon/hop.nvim
    - nvim-lua/plenary.nvim
    - vim-scripts/dbext.vim
    - jbyuki/venn.nvim
    - jbyuki/one-small-step-for-vimkind
- name: Checkout opt vim plugins
  git:
    repo: https://github.com/{{ item }}
    dest: ~/.config/nvim/pack/plugins/opt/{{ item | basename }}
  loop:
    - nvim-treesitter/nvim-treesitter
    - nvim-treesitter/playground
    - saltstack/salt-vim
    - vmchale/dhall-vim
    - hashivim/vim-terraform
    - sirtaj/vim-openscad
    - diepm/vim-rest-console
- name: Checkout vim dev plugins
  git:
    repo: https://github.com/{{ item }}
    dest: ~/.config/nvim/pack/plugins/start/{{ item | basename }}
    update: false
  loop:
    - mfussenegger/nvim-jdtls
    - mfussenegger/nvim-dap
    - mfussenegger/nvim-dap-python
    - mfussenegger/nvim-fzy
    - mfussenegger/nvim-lint
    - mfussenegger/nvim-treehopper
    - mfussenegger/nvim-lsp-compl
