---
- name: Install sway
  become: true
  package:
    state: present
    name:
      - sway
      - swayidle
      - swaylock
      - slurp
      - bemenu
      - wl-clipboard

- name: Install desktop essentials
  become: true
  package:
    state: present
    name:
      - openssh
      - alacritty
      - qutebrowser
      - libnitrokey

- name: Install audio packages
  become: true
  package:
    name:
      - alsa-utils
      - pipewire-pulse
      - pavucontrol

- name: Install fonts
  become: true
  package:
    name:
      - noto-fonts
      - noto-fonts-emoji
      - ttf-roboto
      - ttf-hack

- name: Install i3status-rust
  become: false
  aur:
    name: i3status-rust-git
