---
- name: Clone lua-language-server
  git:
    repo: https://github.com/sumneko/lua-language-server
    dest: ~/dev/sumneko/lua-language-server
    version: dec0117d74e7856fa9950aba7d3fb6647be29079
    recursive: true
    force: true

- name: Cleanup stale stuff
  command: git clean -xdff
  args:
    chdir: ~/dev/sumneko/lua-language-server/

- name: Cleanup stale stuff in submodules
  command: git submodule foreach git clean -xdff
  args:
    chdir: ~/dev/sumneko/lua-language-server/

- name: Make lua-language-server part1
  command: ninja -f ninja/linux.ninja
  args:
    chdir: ~/dev/sumneko/lua-language-server/3rd/luamake
    creates: ~/dev/sumneko/lua-language-server/3rd/luamake/bee.so

- name: Make lua-language-server part2
  command: ./3rd/luamake/luamake rebuild
  args:
    chdir: ~/dev/sumneko/lua-language-server/
    creates: ~/dev/sumneko/bin/Linux/lua-language-server


- name: Install luacheck
  command: luarocks --local install luacheck
  args:
    creates: ~/.luarocks/bin/luacheck
