---
- name: Clone lua-language-server
  git:
    repo: https://github.com/sumneko/lua-language-server
    dest: ~/dev/sumneko/lua-language-server
    recursive: true

- name: Make lua-language-server part1
  command: ninja -f ninja/linux.ninja
  args:
    chdir: ~/dev/sumneko/lua-language-server/3rd/luamake
    creates: ~/dev/sumneko/lua-language-server/3rd/luamake/bee.so

- name: Make lua-language-server part2
  command: ./3rd/luamake/luamake rebuild
  args:
    chdir: ~/dev/sumneko/lua-language-server/
    creates: ~/dev/sumneko/bin/Linux/lua-language-server


- name: Install luacheck
  command: luarocks --local install luacheck
  args:
    creates: ~/.luarocks/bin/luacheck
