---
- name: Create pyls virtualenv
  pip:
    name:
      - pip
      - python-lsp-server
      - yapf
      - mccabe
      - pydocstyle
      - pylsp-mypy
    virtualenv: ~/.virtualenvs/pyls
    virtualenv_command: /usr/bin/python3 -m venv
    state: latest
- name: Symlink pyls
  file:
    src: ~/.virtualenvs/pyls/bin/pylsp
    dest: ~/bin/pylsp
    state: link
