---
- name: Create pyls virtualenv
  pip:
    name:
      - pip
      - python-language-server[pyflakes,yapf,mccabe,pycodestyle,pydocstyle]
    virtualenv: ~/.virtualenvs/pyls
    virtualenv_command: /usr/bin/python3 -m venv
    state: latest
- name: Symlink pyls
  file:
    src: ~/.virtualenvs/pyls/bin/pyls
    dest: ~/bin/pyls
    state: link
