---
- name: Ensure omnisharp folder exists
  file:
    path: ~/apps/omnisharp/
    state: directory
- name: Download and extract omnisharp-roslyn
  unarchive:
    src: https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.37.3/omnisharp-linux-x64.tar.gz
    dest: ~/apps/omnisharp/
    creates: ~/apps/omnisharp/run
    remote_src: true
