---
- name: Ensure omnisharp folder exists
  file:
    path: ~/apps/omnisharp/
    state: directory
- name: Download and extract omnisharp-roslyn
  unarchive:
    src: https://github.com/OmniSharp/omnisharp-roslyn/releases/download/v1.39.1/omnisharp-linux-x64-net6.0.tar.gz
    dest: ~/apps/omnisharp/
    creates: ~/apps/omnisharp/OmniSharp
    remote_src: true

- name: Symlink omnisharp executable
  ansible.builtin.file:
    src: ~/apps/omnisharp/OmniSharp
    dest: ~/bin/OmniSharp
    state: link
