---
- name: Ensure cpptools folder exists
  file:
    path: ~/apps/cpptools
    state: directory

- name: Download cpptools
  unarchive:
    src: https://github.com/microsoft/vscode-cpptools/releases/download/1.7.1/cpptools-linux.vsix
    dest: ~/apps/cpptools/
    remote_src: true

- name: Set executable flag
  file:
    path: ~/apps/cpptools/extension/debugAdapters/bin/OpenDebugAD7
    mode: 0755
