---
- name: Install haskell tooling lts14
  command: stack install --resolver lts-14.3 cabal-install hasktags
  args:
    chdir: ~/
- name: Install haskell tooling lts15
  command: stack install --resolver lts-15.0 ghcid hlint hoogle dhall dhall-json weeder ormolu
  args:
    chdir: ~/
- name: Clone/pull haskell-language-server and ghcid
  git:
    repo: https://github.com/{{ item }}
    dest: ~/dev/{{ item }}
  loop:
    - haskell/haskell-language-server
    - ndmitchell/ghcid
- name: Build haskell-language-server
  command: stack install --stack-yaml=stack-8.8.2.yaml
  args:
    chdir: ~/dev/haskell/haskell-language-server
- name: Generate hoogle database for hie
  command: stack exec hoogle generate
  args:
    chdir: ~/dev/haskell/haskell-language-server
- name: Install ghcid vim plugin
  command: cp -a ~/dev/ndmitchell/ghcid/plugins/nvim ~/.config/nvim/pack/plugins/start/ghcid
