---
- name: Install haskell tooling lts18
  command: stack install --resolver lts-18.22 ghcid hlint hoogle dhall dhall-json ormolu
  args:
    chdir: ~/
- name: Clone/pull haskell-language-server and ghcid
  git:
    repo: https://github.com/{{ item }}
    dest: ~/dev/{{ item }}
  loop:
    - haskell/haskell-language-server
    - ndmitchell/ghcid
- name: Build haskell-language-server
  shell: |
    stack install --stack-yaml stack-{{ item }}.yaml \
      && mv ~/.local/bin/haskell-language-server ~/.local/bin/haskell-language-server-{{ item }}
  args:
    chdir: ~/dev/haskell/haskell-language-server
  loop:
    - 8.10.7
    - 9.0.2
- name: Generate hoogle database for hie
  command: stack exec hoogle generate
  args:
    chdir: ~/dev/haskell/haskell-language-server
- name: Install ghcid vim plugin
  command: cp -a ~/dev/ndmitchell/ghcid/plugins/nvim ~/.config/nvim/pack/plugins/start/ghcid
