---
- name: Clone/pull haskell-ide-engine and ghcid
  git:
    repo: https://github.com/{{ item }}
    dest: ~/dev/{{ item }}
  loop:
    - haskell/haskell-ide-engine
    - ndmitchell/ghcid
- name: Build haskell-ide-engine
  command: stack build --copy-compiler-tool
  args:
    chdir: ~/dev/haskell/haskell-ide-engine
- name: Generate hoogle database for hie
  command: stack exec hoogle generate
  args:
    chdir: ~/dev/haskell/haskell-ide-engine
- name: Install ghcid vim plugin
  command: cp -a ~/dev/ndmitchell/ghcid/plugins/nvim ~/.config/nvim/pack/plugins/start/ghcid
- name: Install haskell tooling
  command: stack install --resolver lts-12.9 ghcid hlint stylish-haskell hoogle dhall dhall-json cabal-install
  args:
    chdir: ~/
