---
- name: Clone vscode-pde
  git:
    repo: https://github.com/testforstephen/vscode-pde
    dest: ~/dev/testforstephen/vscode-pde
    force: true  # npm commands below modify the package.json
    single_branch: true
    depth: 1

- name: Build vscode-pde
  command: npm install
  args:
    chdir: ~/dev/testforstephen/vscode-pde/

- name: Build vscode-pde part2
  command: gulp full_build
  args:
    chdir: ~/dev/testforstephen/vscode-pde/
