---
- name: Fetch and unpack hub
  unarchive:
    src: https://github.com/github/hub/releases/download/v2.5.0/hub-linux-amd64-2.5.0.tgz
    dest: /tmp/
    remote_src: true
- name: Move hub to ~/bin
  copy:
    src: /tmp/hub-linux-amd64-2.5.0/bin/hub
    dest: ~/bin/gh
    mode: 0755
    remote_src: true
- name: Remove /tmp/hub
  file:
    path: /tmp/hub-linux-amd64-2.5.0
    state: absent
