---
- name: Install python based tools
  import_tasks: python_tools.yml
- name: Install TLAToolbox
  import_tasks: tla.yml
- name: Get openapi generator
  get_url:
    url: https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/3.3.4/openapi-generator-cli-3.3.4.jar
    dest: ~/apps/openapi-generator-cli.jar
    checksum: sha256:24cb04939110cffcdd7062d2f50c6f61159dc3e0ca3b8aecbae6ade53ad3dc8c
- name: Get jol
  get_url:
    url: https://repo1.maven.org/maven2/org/openjdk/jol/jol-cli/0.10/jol-cli-0.10-full.jar
    dest: ~/apps/jol.jar
    checksum: sha256:092f29f2034e423c0dba33952afc4211bcba6b5acc01660b3e67e656fc50e82a
