---
- name: Setup tools virtualenv
  pip:
    state: latest
    name:
      - httpie
      - twine
      - shiv
      - wheel
      - vdirsyncer
      - khard
      - yamllint
      - vimg
      - proselint
      - ansible-lint
      - ipython
      - ptpython
      - memory_profiler
      - termgraph
      - debugpy
      - exodus-bundler
      - curlylint
      - llm
      - argostranslate
      - pgcli
    virtualenv: ~/.virtualenvs/tools
    virtualenv_command: /usr/bin/python3 -m venv
- name: Symlink tools
  file:
    src: ~/.virtualenvs/tools/bin/{{ item }}
    dest: ~/bin/{{ item }}
    state: link
  loop:
    - http
    - twine
    - shiv
    - vdirsyncer
    - khard
    - yamllint
    - vimg
    - proselint
    - ansible-lint
    - mprof
    - termgraph
    - curlylint
    - llm
    - argospm
    - argos-translate
    - pgcli
- name: Symlink py -> ptipython
  file:
    src: ~/.virtualenvs/tools/bin/ptipython
    dest: ~/bin/py
    state: link

- name: Bootstrap argospm en_de
  ansible.builtin.command: argospm install translate-en_de
  args:
    creates: ~/.local/cache/argos-translate/downloads/translate-en_de.argosmodel

- name: Bootstrap argospm de_en
  ansible.builtin.command: argospm install translate-de_en
  args:
    creates: ~/.local/cache/argos-translate/downloads/translate-de_en.argosmodel
