---
- name: Setup tools virtualenv
  pip:
    name:
      - httpie
      - twine
      - shiv
      - wheel
      - randrctl
      - vdirsyncer
      - khard
      - yamllint
      - vimg
      - jarg
    virtualenv: ~/.virtualenvs/tools
    virtualenv_command: /usr/bin/python3 -m venv
- name: Symlink tools
  file:
    src: ~/.virtualenvs/tools/bin/{{ item }}
    dest: ~/bin/{{ item }}
    state: link
  loop:
    - http
    - twine
    - shiv
    - randrctl
    - vdirsyncer
    - khard
    - yamllint
    - vimg
    - jarg
