---
- hosts: localhost
  gather_facts: true
  roles:
    - stow
    - aur
  tasks:
    - name: Install dev packages
      become: true
      package:
        name:
          - jq
          - ripgrep
          - bash-language-server
          - hub
          - luarocks
          - ninja
          - fzf

    - name: Install packages for term2mp4.hs
      become: true
      package:
        name:
          - asciinema
          - ffmpeg
          - xclip
    - name: Install asciicast2gif
      aur:
        name: nodejs-asciicast2gif

    - name: Symlink libpcre for comby
      become: true
      file:
        src: /usr/lib/libpcre.so
        dest: /usr/lib/libpcre.so.3
        state: link
