---
- hosts: localhost
  gather_facts: true
  roles:
    - stow
    - dev
    - desktop
    - aur
  tasks:
    - name: Symlink libpcre for comby
      become: true
      file:
        src: /usr/lib/libpcre.so
        dest: /usr/lib/libpcre.so.3
        state: link
